# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Xsoftware\Python\workstation\MDLStore_v1.0\MDLStore\UI\main_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainAppPage(object):
    def setupUi(self, MainAppPage):
        MainAppPage.setObjectName("MainAppPage")
        MainAppPage.resize(836, 639)
        self.horizontalLayout = QtWidgets.QHBoxLayout(MainAppPage)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(MainAppPage)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.left_widget = QtWidgets.QListWidget(self.frame)
        self.left_widget.setObjectName("left_widget")
        self.verticalLayout.addWidget(self.left_widget)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.horizontalLayout_2.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(MainAppPage)
        QtCore.QMetaObject.connectSlotsByName(MainAppPage)

    def retranslateUi(self, MainAppPage):
        _translate = QtCore.QCoreApplication.translate
        MainAppPage.setWindowTitle(_translate("MainAppPage", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainAppPage = QtWidgets.QWidget()
    ui = Ui_MainAppPage()
    ui.setupUi(MainAppPage)
    MainAppPage.show()
    sys.exit(app.exec_())
